### ISSUE TITLE
Aktualizacja Smogomierz Homebridge

### ISSUE THREAD

**Issue by mickelk** [bfaliszek/homebridge-smogomierz#2]
Cześć, mam problem z aktualizacją wtyczki Smogomierza dla Homebridge.
Z tego co znalazłem wymagana jest aktualizacja node.js do nowszej wersji, aktualnie mam v8.14.0 a wymagana jest raczej 11.
Mam malinkę 3 B+, po zaktualizowaniu mam problem z główną wtyczką homebridge. NIe uruchamia, nie działa.
Czy jest ktoś na sali kto jest mi w stanie pomóc ?

**Comment by bfaliszek** [comment]
Spróbuj odinstalować starą wtyczkę oraz HB i zainstalować jeszcze raz. Robiłem kilka dni temu czystą instalację z najnowszymi wersjami i wszystko działało.

**Comment by mickelk** [comment]
po wielu próbach udało mi się zaktualizować node do wersji v11.10.0, po aktualizacji wtyczki Smogomierz do wersji v1.2.0 mam coś takiego:

[2019-2-17 12:55:31] [Smogomierz Air Quality] Initializing Smogomierz accessory...
[2019-2-17 12:55:31] [Smogomierz Air Quality] Smogomierz is working

/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:75
    if (existing.UUID === characteristic.UUID) {
                                         ^
TypeError: Cannot read property 'UUID' of undefined
    at Service.AirQualitySensor.Service.addCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:75:42)
    at AirAccessory.getServices (/usr/local/lib/node_modules/homebridge-smogomierz/index.js:152:20)
    at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:410:36)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:298:26)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:87:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)

po powrocie na wersje v1.1.3 działa bez problemu

**Comment by huczas** [comment]
Wygląda na to że mam ten sam problem, 
```
[2/19/2019, 7:36:38 AM] Loading 3 accessories...
[2/19/2019, 7:36:38 AM] [Smogomierz Air Quality] Initializing Smogomierz accessory...
[2/19/2019, 7:36:38 AM] [Smogomierz Air Quality] Smogomierz is working
/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:75
    if (existing.UUID === characteristic.UUID) {
                                         ^

TypeError: Cannot read property 'UUID' of undefined
    at Service.AirQualitySensor.Service.addCharacteristic (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:75:42)
    at AirAccessory.getServices (/usr/lib/node_modules/homebridge-smogomierz/index.js:152:20)
    at Server._createAccessory (/usr/lib/node_modules/homebridge/lib/server.js:410:36)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:298:26)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:87:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
```
Najnowsza wtyczka, i nodejs:
pi@raspberrypi:~ $ node -v
v11.10.0

**Comment by hejsiri** [comment]
Coś jest na rzeczy, na innej czystej instalacji HB to samo.

**Comment by huczas** [comment]
instalacja (sudo) npm install -g homebridge-smogomierz@1.1.3 (starsza wersja) działa

**Comment by hejsiri** [comment]
Zdaje się, że sporo osób zaleca node.js w wersji 8.9.4 bo działa stabilnie i pewne problemy z nieodpowiadającymi akcesoriami w tej wersji znikają. Właśnie się o tym przekonałem. Może warto zrobić kompatybilność z wersją  8.9.4+ ??

**Comment by bfaliszek** [comment]
Zmieniłem na 8.9.4 - https://github.com/bfaliszek/homebridge-smogomierz/commit/72eb396fefba2e453efc38a0430306db00466244#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L23

**Comment by hejsiri** [comment]
node.js v11.13.0 nadal nie udaje się uruchomić...

	Apr 07 11:18:50 HomeBridge homebridge[18473]: [4/7/2019, 11:18:50 AM] [Smogomierz]    Smogomierz is working
	Apr 07 11:18:50 HomeBridge homebridge[18473]: [4/7/2019, 11:18:50 AM] TypeError: Cannot read property 'UUID' of undefined
	Apr 07 11:18:50 HomeBridge homebridge[18473]:     at Service.AirQualitySensor.Service.addCharacteristic (/usr/lib/node_modules/hap-nodejs/lib/Service.js:75:42)
	Apr 07 11:18:50 HomeBridge homebridge[18473]:     at AirAccessory.getServices (/usr/lib/node_modules/homebridge-smogomierz/index.js:152:20)
	Apr 07 11:18:50 HomeBridge homebridge[18473]:     at Server._createAccessory (/usr/lib/node_modules/homebridge/lib/server.js:427:36)
	Apr 07 11:18:50 HomeBridge homebridge[18473]:     at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:309:26)
	Apr 07 11:18:50 HomeBridge homebridge[18473]:     at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:91:38)
	Apr 07 11:18:50 HomeBridge homebridge[18473]:     at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
	Apr 07 11:18:50 HomeBridge homebridge[18473]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
	Apr 07 11:18:50 HomeBridge homebridge[18473]:     at Module._compile (internal/modules/cjs/loader.js:805:30)
	Apr 07 11:18:50 HomeBridge homebridge[18473]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
	Apr 07 11:18:50 HomeBridge homebridge[18473]:     at Module.load (internal/modules/cjs/loader.js:672:32)

**Comment by ookris** [comment]
Node w wersji 8.9.4 i dalej błąd. 
```
homebridge@homebridge:~$ homebridge
[2019-4-11 18:28:47] Loaded config.json with 1 accessories and 0 platforms.
[2019-4-11 18:28:47] ---
[2019-4-11 18:28:47] Loaded plugin: homebridge-smogomierz
[2019-4-11 18:28:47] Registering accessory 'homebridge-smogomierz.Smogomierz'
[2019-4-11 18:28:47] ---
[2019-4-11 18:28:47] Loading 1 accessories...
[2019-4-11 18:28:47] [Smogomierz Air Quality] Initializing Smogomierz accessory...
[2019-4-11 18:28:47] [Smogomierz Air Quality] Smogomierz is working
[2019-4-11 18:28:47] TypeError: Cannot read property 'UUID' of undefined
    at Service.AirQualitySensor.Service.addCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Service.js:75:42)
    at AirAccessory.getServices (/usr/local/lib/node_modules/homebridge-smogomierz/index.js:152:20)
    at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:427:36)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:309:26)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
[2019-4-11 18:28:47] Got SIGTERM, shutting down Homebridge...
homebridge@homebridge:~$
```

**Comment by hejsiri** [comment]
bo błąd jest nieznanej charakterystyce HK. Zgłaszałem już to wcześniej. Zreszta wystarczy zajrzeć do historii pliku index.js. Posypało się po dodaniu dodatkowych charakterystyk. 
Teraz przy włączonej funkcji usypiania i tak plugin jest bezużyteczny. Może uda mi się coś zrobić w oparciu o MQTT.

Plugin Smogomierz MQTT #3

**Comment by hejsiri** [comment]
wiersz 86.


         temperatureService.setCharacteristic(Characteristic.AtmosphericPressureLevel, roundInt(data.pressure));

chyba nie "temperatureService"

**Comment by bfaliszek** [comment]
Przywróciłem poprzednią działającą wersję wtyczki. Po aktualizacji do 1.2.2 powinna znowu działać.

**Comment by mickelk** [comment]
> Przywróciłem poprzednią działającą wersję wtyczki. Po aktualizacji do 1.2.2 powinna znowu działać.

potwierdzam, działa ;)

**Comment by ookris** [comment]
> > Przywróciłem poprzednią działającą wersję wtyczki. Po aktualizacji do 1.2.2 powinna znowu działać.
> 
> potwierdzam, działa ;)

Z jaką wersją Nodejs?

**Comment by mickelk** [comment]
> > > Przywróciłem poprzednią działającą wersję wtyczki. Po aktualizacji do 1.2.2 powinna znowu działać.
> > 
> > 
> > potwierdzam, działa ;)
> 
> Z jaką wersją Nodejs?

11.12.0

**Comment by ookris** [comment]
Potwierdzam. Wszystko ładnie działa.
